<a href="https://colab.research.google.com/github/he16946/Data_Labs/blob/master/bootstrap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook you'll create your own bootstrap function following the bootstrap algorithm (check the lecture notes!)

In [0]:
import matplotlib
import pandas as pd
import seaborn as sns
import numpy as np



In [119]:
# Load the data
df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab2%20-%20bootstrap/customers.csv')
data = df.values.T[1]

for i in range(0,5):
  r = np.random.randint(1,100)
  samp = df.sample(n=14, replace=True, random_state= r)
  boot = samp.values.T[1]
  mean = boot.mean()
  mean_array = np.append(mean_array, mean)
  boot_array = np.vstack((boot_array, boot))
  
print(mean_array)
print(boot_array)





[ 2.          2.          2.          8.          8.          8.85714286
  6.71428571  8.85714286 13.28571429 10.78571429  9.5        12.21428571
  8.         10.42857143  9.14285714  8.71428571  7.14285714  9.78571429
 10.14285714  7.21428571 11.85714286  6.92857143  9.42857143  7.71428571
 11.71428571 11.5         9.92857143 12.21428571  8.85714286  8.35714286
  7.57142857  8.07142857  8.28571429  7.14285714  8.35714286 10.42857143
 12.71428571  7.64285714  8.5         9.92857143  9.5         7.71428571]
[[ 9. 20.  8.  8.  2. 22.  8.  8. 10. 10. 10.  8.  5.  5.]
 [ 9. 20.  8.  8.  2. 22.  8.  8. 10. 10. 10.  8.  5.  5.]
 [10.  4.  8.  9. 22. 22. 20.  8.  7.  8. 20. 13.  2.  8.]
 [22. 13.  2.  9.  9.  2.  8.  9.  9.  9.  7. 22.  2. 22.]
 [20.  2. 20.  9.  5.  9.  5.  9. 20.  7.  2.  9.  7.  8.]
 [13. 22. 22. 22.  2.  9. 22. 10.  9.  8. 20.  2.  8.  2.]
 [10.  2.  4.  8.  8.  9.  7.  8.  8. 20. 22.  9.  7.  2.]
 [ 2.  2.  9.  5. 13.  9.  5. 13.  9.  2.  8. 22.  9.  9.]
 [22.  2.  8.  2

In [0]:
# Checking the notes from the lecture, create here your own bootstrap function:
# 1. Create an array of samples of shape (n_iterations, sample_size)
# 2. Calculate and save the mean of the array (this is "data_mean" that is returned by the function)
# 3. In each iteration:
# 3.1 Get the data corresponding to that iteration (new_samples[iteration, :])
# 3.2 Calculate the mean of the iteration data and store it
# (At this point you should have an array of n_iterations values)
# 4. Calculate the lower and upper bounds for a 95% CI (hint: check the percentile function on Numpy)
# 5. Return data_mean, and the lower and upper bounds of your interval
def boostrap_mean(sample, sample_size, n_iterations):
	# <---INSERT YOUR CODE HERE--->

	return data_mean, lower, upper


In [0]:
# Call your bootstrap function and plot the results

boots = []
for i in range(100, 100000, 1000):
    boot = boostrap_mean(data, data.shape[0], i)
    boots.append([i, boot[0], "mean"])
    boots.append([i, boot[1], "lower"])
    boots.append([i, boot[2], "upper"])

df_boot = pd.DataFrame(boots, columns=['Boostrap Iterations', 'Mean', "Value"])
sns_plot = sns.lmplot(df_boot.columns[0], df_boot.columns[1], data=df_boot, fit_reg=False, hue="Value")

sns_plot.axes[0, 0].set_ylim(0,)
sns_plot.axes[0, 0].set_xlim(0, 100000)

#sns_plot.savefig("bootstrap_confidence.png", bbox_inches='tight')
#sns_plot.savefig("bootstrap_confidence.pdf", bbox_inches='tight')




Now, modify the bootstrap function so that you can pass your desired confidence interval as a parameter.



In [0]:
def boostrap_mean_ci(sample, sample_size, iterations, ci):
	# <---INSERT YOUR CODE HERE--->
	return data_mean, lower, upper

In [0]:

boots = []
for i in range(100, 100000, 1000):
    boot = boostrap_mean_ci(data, data.shape[0], i, 80)
    boots.append([i, boot[0], "mean"])
    boots.append([i, boot[1], "lower"])
    boots.append([i, boot[2], "upper"])

df_boot = pd.DataFrame(boots, columns=['Boostrap Iterations', 'Mean', "Value"])
sns_plot = sns.lmplot(df_boot.columns[0], df_boot.columns[1], data=df_boot, fit_reg=False, hue="Value")

sns_plot.axes[0, 0].set_ylim(0,)
sns_plot.axes[0, 0].set_xlim(0, 100000)

sns_plot.savefig("bootstrap_confidence_80.png", bbox_inches='tight')
sns_plot.savefig("bootstrap_confidence_80.pdf", bbox_inches='tight')


# Vehicles dataset

Now let's work on a different dataset. Load the vehicles.csv file and check the Moodle page for instructions on how to proceed


In [0]:
# Load and visualise the vehicles dataset
# <---INSERT YOUR CODE HERE--->
# Note: you can add more cells as needed to organise your code and your plots


In [0]:
# Compare the two fleets.
# You can create a permutation test function to do this. Check the lecture notes!